### ISSUE TITLE
Id type: string?

### ISSUE THREAD

**Issue by mpollmeier** [mpollmeier/orientdb-gremlin#12]
I was thinking of changing the ID type to a String (it's ORecordId at the moment)

My reasoning is that if people decide to have the vertex IDs in their domain classes (which represent a vertex), then Orient's types don't leak into the domain entity (if they are Strings). And it's easy to convert a String back into a ORecordId in the driver. 

On the other side, @mourednik remarked (rightly so) that it's a bad idea to use the vertex id inside your domain entity anyway, as they are just technical database ids. Instead you should use your own id for this, which you index and maintain separately. 

@velo do you have an opinion on this?

**Comment by velo** [comment]
We could have our own type.... that allow you from and to ORecordId (and String)
