### ISSUE TITLE
Bump tinkerpop version to 3.0.2

### ISSUE THREAD

**Issue by velo** [mpollmeier/orientdb-gremlin#14]
http://tinkerpop.incubator.apache.org/docs/3.0.2-incubating/upgrade.html#_tinkerpop_3_0_2
https://issues.apache.org/jira/browse/TINKERPOP3/fixforversion/12333356/?selectedTab=com.atlassian.jira.jira-projects-plugin:version-summary-panel

**Comment by Jotschi** [comment]
I included this in #17
