### ISSUE TITLE
addEdge

### ISSUE THREAD

**Issue by M1sterPl0w** [mpollmeier/orientdb-gremlin#158]
In followed the following documentation:  http://orientdb.com/docs/3.0.x/gremlin/Gremlin.html 
Here is told you can make vertices with addVertex en create edges with addEdge. The last one is not present in "OrientGraph.java" please update the documentation or something.

**Comment by wolf4ood** [comment]
Hi @M1sterPl0w 

that link is for Gremlin API 2.6.x. For the version 3.0.x which is compatible with Apache Tinkerpop 3 see
[here](http://orientdb.com/docs/3.0.x/tinkerpop3/OrientDB-TinkerPop3.html)
