### ISSUE TITLE
How to get vertex class name with gremlin console?

### ISSUE THREAD

**Issue by SafinRR** [mpollmeier/orientdb-gremlin#165]
Hello!
How to get vertex class  and name rid  with gremlin console?

 g.V('#48:19').valueMap()
g.V('#48:19').properties()

**Comment by wolf4ood** [comment]
Hi @SafinRR 

```
g.V('#48:19').valueMap(true)
```

in the version supported by ODB

in future version of Gremlin 3.4.x

http://tinkerpop.apache.org/docs/current/reference/#valuemap-step
