### ISSUE TITLE
Maven Group ID in pom.xml is not the official one?

### ISSUE THREAD

**Issue by kuzeko** [mpollmeier/orientdb-gremlin#172]
Hi, 
is it normal that the release here has this group id `com.michaelpollmeier`
instead of `com.orientechnologies` ?

https://github.com/orientechnologies/orientdb-gremlin/blob/de68af5d2aa95a56087efde302ba6a89278a16fc/driver/pom.xml#L4

As a result  on the maven central we have

https://search.maven.org/artifact/com.michaelpollmeier/orientdb-gremlin/3.2.3.0/jar

and the official is stuck to 3.1.x

https://mvnrepository.com/artifact/com.orientechnologies/orientdb-gremlin

**Comment by wolf4ood** [comment]
Hi @kuzeko 

the group is not anymore  `com.michaelpollmeier` check [here](https://github.com/orientechnologies/orientdb-gremlin/blob/3.0.x/driver/pom.xml#L5)

and the release is not tucket to 3.1.x. 

https://mvnrepository.com/artifact/com.orientechnologies/orientdb-gremlin

This repo follows the versioning of OrientDB which now the last stable is 3.0.30.

Let me know if it helps.

Thanks

**Comment by kuzeko** [comment]
I see,
I got confused from the tags and didn't check the timestamp.
Sorry for the confusion

**Comment by wolf4ood** [comment]
👍
