### ISSUE TITLE
[question] Matching step support?

### ISSUE THREAD

**Issue by velo** [mpollmeier/orientdb-gremlin#7]
Hi,

As it is right now, does match step works?
http://tinkerpop.incubator.apache.org/docs/3.0.1-incubating/#match-step

If not, any pointers in case I decide to make it happen?

Thanks,

Marvin

**Comment by mpollmeier** [comment]
I am not sure why it wouldn't. Give it a try and let me know :)

**Comment by velo** [comment]
I did and no joy... but, it may be me =D

I will retry tomorrow

**Comment by mpollmeier** [comment]
not sure what the problem is, but here's an example of the match step in tinkergraph using gremlin-scala: https://github.com/mpollmeier/gremlin-scala-examples/blob/master/tinkergraph/src/test/scala/MovieLensSpec.scala#L178
