### ISSUE TITLE
OrientDB 2.2.0

### ISSUE THREAD

**Issue by ddrozdov** [mpollmeier/orientdb-gremlin#73]
2.2.0 has been released a couple of days ago. Are there any plans to upgrade?

**Comment by velo** [comment]
I tried to, many tests failed.

**Comment by velo** [comment]
I made a pull request with my changes:
https://github.com/mpollmeier/orientdb-gremlin/pull/74
In case you wanna pick where I dropped!

**Comment by wildroco** [comment]
👍

**Comment by wildroco** [comment]
How's going on this issue?
I really hope to use v2.2.0 with this lovely driver!

**Comment by velo** [comment]
I have no idea how to fix it

What I can do it's done https://github.com/mpollmeier/orientdb-gremlin/pull/74

**Comment by wildroco** [comment]
It is awesome that merged #74 successfully!

Could you release this one?

**Comment by mpollmeier** [comment]
just released 3.2.1.1 which upgrades to OrientDB 2.2 :)
