### ISSUE TITLE
Usage and scalability

### ISSUE THREAD

**Issue by ErwanDemairy** [mpollmeier/orientdb-gremlin#76]
Hello, 
I am trying to build requests for a DB of around 10 millions edges.
I was surprised to see requests such as graph.traversal.E().hasNext() or graph.traversal.E().limit(1).toList() stuck until the memory is saturated: it appears these requests launch a full load of the database.
So my question: am I writing the requests correctly, especially with regards to how many edges or vertices are loaded in memory for a given request, since the DB does not fit in the available memory ?
Any advice helping to solve this issues would be more than welcome :)
Erwan

**Comment by mpollmeier** [comment]
sorry for being quiet about this. this is not the official driver with support from the orient crew, but rather an implementation that works well for the use cases of the current contributors (mostly @velo and myself). it's not optimised for big scenarios like yours and has a few shortcomings around indices. I'll review the readme to make things more clear.

**Comment by velo** [comment]
But, if you wanna help us solve this, pull requests are more them welcome!
