### ISSUE TITLE
Roadmal for orientdb-gremlin

### ISSUE THREAD

**Issue by jCalamari** [mpollmeier/orientdb-gremlin#81]
Hi,

sorry for creating a github issue. I was not sure how to approach it.
Is there a roadmap for the project? Are you planning on upgrading to OrientDB 2.2 any time soon?

Thanks

**Comment by velo** [comment]
There is a pull request for 2.2 in place, but, tests fail and I have no
idea why.

You are welcome to amend it.

**Comment by velo** [comment]
https://github.com/mpollmeier/orientdb-gremlin/pull/74

**Comment by mpollmeier** [comment]
just released 3.2.1.1 which upgrades to OrientDB 2.2 :)
