### ISSUE TITLE
Release for OrientDB 2.1.17

### ISSUE THREAD

**Issue by jCalamari** [mpollmeier/orientdb-gremlin#84]
Hi guys,
Any chances for getting a release of orient-gremlin with OrientDB 2.1.17?
Thanks!

**Comment by mpollmeier** [comment]
i'll shortly release one for 2.1.20, I hope that suits your needs?

**Comment by mpollmeier** [comment]
released now, should be in mvn central shortly

**Comment by jCalamari** [comment]
@mpollmeier  Thank you very much!
